import {
  FaLeaf, FaTractor, FaHammer, FaCar, FaIndustry, FaFlask,
  FaHamburger, FaCoffee, FaTshirt, FaLaptopCode, FaMicrochip,
  FaHardHat, FaBuilding, FaMoneyBillWave, FaLandmark, FaHeartbeat,
  FaStethoscope, FaShoppingCart, FaTruck, FaGraduationCap, FaFilm,
  FaGamepad, FaBriefcase, FaUserTie, FaSolarPanel, FaBalanceScale,
  FaGlobe, FaBolt, FaShip, FaPlane, FaTrain, FaRecycle
} from "react-icons/fa";

export const industries = [
  { name: "Agriculture & Farming", icon: FaLeaf },
  { name: "Crop Farming", icon: FaTractor },
  { name: "Horticulture", icon: FaLeaf },
  { name: "Floriculture", icon: FaLeaf },
  { name: "Organic Farming", icon: FaLeaf },
  { name: "Greenhouse Farming", icon: FaLeaf },
  { name: "Plantation (Tea, Coffee, Rubber)", icon: FaLeaf },
  { name: "Seed Production", icon: FaLeaf },
  { name: "Agrochemicals & Fertilizers", icon: FaFlask },
  { name: "Animal & Livestock", icon: FaGlobe },
  { name: "Dairy Farming & Processing", icon: FaHamburger },
  { name: "Poultry Farming", icon: FaHamburger },
  { name: "Fisheries & Aquaculture", icon: FaShip },
  { name: "Animal Feed & Nutrition", icon: FaLeaf },
  { name: "Veterinary Services", icon: FaStethoscope },
  { name: "Forestry & Logging", icon: FaLeaf },
  { name: "Mining & Extraction", icon: FaHammer },
  { name: "Coal Mining", icon: FaHammer },
  { name: "Metal Mining", icon: FaHammer },
  { name: "Non-Metal Mining", icon: FaHammer },
  { name: "Sand & Stone Quarrying", icon: FaHammer },
  { name: "Automobile & Auto Components", icon: FaCar },
  { name: "Aerospace & Aviation", icon: FaPlane },
  { name: "Shipbuilding", icon: FaShip },
  { name: "Railways & Locomotives", icon: FaTrain },
  { name: "Industrial Machinery", icon: FaIndustry },
  { name: "Chemical & Petrochemical", icon: FaFlask },
  { name: "Paints & Coatings", icon: FaFlask },
  { name: "Plastics & Rubber", icon: FaIndustry },
  { name: "Adhesives & Sealants", icon: FaFlask },
  { name: "Dyes & Pigments", icon: FaFlask },
  { name: "Glass & Ceramics", icon: FaBuilding },
  { name: "Pharmaceutical Formulations", icon: FaHeartbeat },
  { name: "Biotechnology Products", icon: FaFlask },
  { name: "Medical Devices", icon: FaStethoscope },
  { name: "Ayurvedic & Herbal", icon: FaLeaf },
  { name: "Meat & Seafood Processing", icon: FaHamburger },
  { name: "Beverages", icon: FaCoffee },
  { name: "Packaged Food & FMCG", icon: FaShoppingCart },
  { name: "Bakery & Confectionery", icon: FaHamburger },
  { name: "Edible Oils", icon: FaFlask },
  { name: "Yarn & Spinning Mills", icon: FaTshirt },
  { name: "Garment & Textile", icon: FaTshirt },
  { name: "Embroidery & Fashion Design", icon: FaTshirt },
  { name: "Leather & Footwear", icon: FaTshirt },
  { name: "Home Textiles", icon: FaTshirt },
  { name: "Beauty & Personal Care", icon: FaShoppingCart },
  { name: "Consumer Electronics", icon: FaMicrochip },
  { name: "Electrical Appliances", icon: FaBolt },
  { name: "Batteries & Power Systems", icon: FaBolt },
  { name: "Cables & Wires", icon: FaBolt },
  { name: "Steel, Metals & Foundry", icon: FaIndustry },
  { name: "Fabrication Units", icon: FaIndustry },
  { name: "Cement Manufacturing", icon: FaBuilding },
  { name: "Tiles & Ceramics", icon: FaBuilding },
  { name: "Ready-Mix Concrete", icon: FaTruck },
  { name: "Building & Construction", icon: FaHardHat },
  { name: "Plastic Packaging", icon: FaIndustry },
  { name: "Corrugated Boxes", icon: FaIndustry },
  { name: "Labels & Stickers", icon: FaIndustry },
  { name: "Printing Press & Media", icon: FaIndustry },
  { name: "Modular Furniture", icon: FaBuilding },
  { name: "Residential & Commercial Real Estate", icon: FaBuilding },
  { name: "Real Estate Brokerage", icon: FaBriefcase },
  { name: "Roads & Infrastructure", icon: FaHardHat },
  { name: "Smart City & Urban Development", icon: FaBuilding },
  { name: "Architecture & Interior Design", icon: FaBuilding },
  { name: "Public & Private Banking", icon: FaLandmark },
  { name: "NBFC", icon: FaMoneyBillWave },
  { name: "Microfinance", icon: FaMoneyBillWave },
  { name: "Stockbroking", icon: FaMoneyBillWave },
  { name: "Mutual Funds", icon: FaMoneyBillWave },
  { name: "Fintech & Payment Solutions", icon: FaLaptopCode },
  { name: "Investment & Wealth Management", icon: FaMoneyBillWave },
  { name: "Life Insurance", icon: FaHeartbeat },
  { name: "Health Insurance", icon: FaHeartbeat },
  { name: "General Insurance", icon: FaHeartbeat },
  { name: "Reinsurance", icon: FaHeartbeat },
  { name: "Software Development", icon: FaLaptopCode },
  { name: "Cloud Computing", icon: FaLaptopCode },
  { name: "Cybersecurity", icon: FaLaptopCode },
  { name: "IT Services & Consulting", icon: FaLaptopCode },
  { name: "Data Analytics & AI", icon: FaLaptopCode },
  { name: "Web & App Development", icon: FaLaptopCode },
  { name: "Hardware & Networking", icon: FaMicrochip },
  { name: "Telecom Equipment", icon: FaMicrochip },
  { name: "Mobile Network Operators", icon: FaMicrochip },
  { name: "Call Centers", icon: FaUserTie },
  { name: "Financial KPO", icon: FaMoneyBillWave },
  { name: "Healthcare BPO", icon: FaStethoscope },
  { name: "Technical Support", icon: FaLaptopCode },
  { name: "Hospitals & Clinics", icon: FaHeartbeat },
  { name: "Diagnostic Labs", icon: FaStethoscope },
  { name: "Wellness & Fitness", icon: FaHeartbeat },
  { name: "Physiotherapy", icon: FaStethoscope },
  { name: "Mental Health Clinics", icon: FaHeartbeat },
  { name: "Supermarkets & Retail", icon: FaShoppingCart },
  { name: "Online Marketplaces", icon: FaShoppingCart },
  { name: "Consumer Durables", icon: FaShoppingCart },
  { name: "Jewellery Stores", icon: FaShoppingCart },
  { name: "Transportation", icon: FaTruck },
  { name: "Courier & Cargo", icon: FaPlane },
  { name: "Warehousing", icon: FaBuilding },
  { name: "3PL & 4PL Logistics", icon: FaTruck },
  { name: "Cold Chain Logistics", icon: FaTruck },
  { name: "Import-Export", icon: FaShip },
  { name: "Hotels & Resorts", icon: FaBuilding },
  { name: "Restaurants & Catering", icon: FaHamburger },
  { name: "Travel Agencies", icon: FaPlane },
  { name: "Airlines", icon: FaPlane },
  { name: "Cruises", icon: FaShip },
  { name: "Facility Management", icon: FaBuilding },
  { name: "Event Management", icon: FaUserTie },
  { name: "Security Services", icon: FaUserTie },
  { name: "Oil & Gas", icon: FaIndustry },
  { name: "Renewable Energy", icon: FaSolarPanel },
  { name: "Power Utilities", icon: FaBolt },
  { name: "Waste Management", icon: FaRecycle },
  { name: "Schools & Universities", icon: FaGraduationCap },
  { name: "Vocational Training", icon: FaGraduationCap },
  { name: "EdTech Platforms", icon: FaLaptopCode },
  { name: "Skill Development", icon: FaGraduationCap },
  { name: "Advertising & Marketing", icon: FaUserTie },
  { name: "Film & Television", icon: FaFilm },
  { name: "Music Production", icon: FaFilm },
  { name: "Animation & Design", icon: FaLaptopCode },
  { name: "Gaming & Esports", icon: FaGamepad },
  { name: "Legal Services", icon: FaBalanceScale },
  { name: "Accounting Firms", icon: FaBriefcase },
  { name: "Business Consulting", icon: FaBriefcase },
  { name: "Market Research", icon: FaBriefcase },
  { name: "HR & Recruitment", icon: FaUserTie },
  { name: "NGO & Social Sector", icon: FaGlobe },
  { name: "Scientific Research", icon: FaFlask },
  { name: "Biotechnology", icon: FaFlask },
  { name: "Space Technology", icon: FaPlane },
  { name: "Robotics", icon: FaMicrochip },
  { name: "Nanotechnology", icon: FaFlask },
  { name: "Electric Vehicles (EV)", icon: FaCar },
  { name: "Drone Manufacturing", icon: FaPlane },
  { name: "Smart Devices & IoT", icon: FaLaptopCode },
  { name: "Blockchain & Crypto", icon: FaLaptopCode },
  { name: "Green Technology", icon: FaLeaf }
];
